FROM python:3.8-slim

LABEL maintener Dilon Santos <dilonsts@gmail.com>
LABEL description "Dockerfile para criar imagem do exporter"

WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt

CMD python3 exporter.py
